import type {
  PaymentGate,
  TimelineAlert,
  TimelineProject,
  WorkPackage,
} from './types';

export const demoTimelineProject: TimelineProject = {
  id: 'project-villa-athani',
  name: 'Villa, Athani',
  clientName: 'Rafeek Muhammed Ali',
  projectType: 'Villa Interior - Dummy Client Timeline',
  status: 'active',
  startDate: '2026-05-18',
  expectedHandoverDate: '2026-07-04',
  currentProjectedHandoverDate: '2026-07-04',
  revenue: 475473,
  location: 'Athani, Kerala',
};

export const demoPaymentGates: PaymentGate[] = [
  {
    id: 'gate-before-texture-paint',
    projectId: 'project-villa-athani',
    type: 'major_site_execution',
    title: 'Stage 1 Completion',
    description: 'After Fabrication Part-A',
    percentage: 35,
    amount: 166416,
    dueDate: '2026-05-23',
    status: 'pending',
    blocksWorkPackageIds: ['wp-texture-paint-exterior'],
  },
  {
    id: 'gate-after-texture-paint',
    projectId: 'project-villa-athani',
    type: 'procurement_start',
    title: 'Stage 2 Completion',
    description: 'After Stage 2 Finishes',
    percentage: 30,
    amount: 142642,
    dueDate: '2026-05-30',
    status: 'pending',
    blocksWorkPackageIds: [
      'wp-fixed-glass-sliding-part-b',
      'wp-work-area-aluminium-cabinets',
    ],
  },
  {
    id: 'gate-before-final-installation',
    projectId: 'project-villa-athani',
    type: 'final_installation',
    title: 'Stage 3 Readiness',
    description: 'Before Final Installation Starts',
    percentage: 25,
    amount: 118868,
    dueDate: '2026-06-28',
    status: 'pending',
    blocksWorkPackageIds: [
      'wp-fixed-glass-sliding-part-b',
      'wp-work-area-aluminium-cabinets',
      'wp-furniture-wood-factory',
    ],
  },
  {
    id: 'gate-final-handover',
    projectId: 'project-villa-athani',
    type: 'handover',
    title: 'Final Handover',
    description: 'At Final Handover',
    percentage: 10,
    amount: 47547,
    dueDate: '2026-07-04',
    status: 'pending',
    blocksWorkPackageIds: ['wp-final-site-handover'],
  },
];

export const demoWorkPackages: WorkPackage[] = [
  {
    id: 'wp-fixed-glass-sliding-part-a',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Fixed Glass Windows and Sliding Doors Part A',
    description:
      'Immediate fixed glass and sliding door works required before exterior texture painting.',
    assigneeName: 'Akhil',
    department: 'design_execution',
    estimatedStartDate: '2026-05-18',
    estimatedEndDate: '2026-05-19',
    estimatedDurationDays: 2,
    status: 'ready',
    priority: 'critical',
    dependsOnWorkPackageIds: [],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-glass-partitions-bathrooms',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Glass Partitions for Bathrooms',
    description:
      'Bathroom glass partition fixing. Planned as a quick one-day activity.',
    assigneeName: 'Nikhil',
    department: 'design_execution',
    estimatedStartDate: '2026-05-18',
    estimatedEndDate: '2026-05-18',
    estimatedDurationDays: 1,
    status: 'ready',
    priority: 'high',
    dependsOnWorkPackageIds: [],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-steel-roof-finishing',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Steel Roof - Finishing Works',
    description:
      'Steel roof finishing works scheduled after the first glass and bathroom partition works are completed.',
    assigneeName: 'Jijo',
    department: 'design_execution',
    estimatedStartDate: '2026-05-20',
    estimatedEndDate: '2026-05-22',
    estimatedDurationDays: 3,
    status: 'ready',
    priority: 'critical',
    dependsOnWorkPackageIds: [
      'wp-fixed-glass-sliding-part-a',
      'wp-glass-partitions-bathrooms',
    ],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-texture-paint-exterior',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Texture Paint - Exterior',
    description:
      'Exterior texture paint starts only after Part A glass, bathroom partitions, steel roof finishing, and payment confirmation.',
    assigneeName: 'Srikanth',
    department: 'design_execution',
    estimatedStartDate: '2026-05-23',
    estimatedEndDate: '2026-06-02',
    estimatedDurationDays: 11,
    status: 'blocked_by_payment',
    priority: 'critical',
    paymentGateId: 'gate-before-texture-paint',
    dependsOnWorkPackageIds: [
      'wp-fixed-glass-sliding-part-a',
      'wp-glass-partitions-bathrooms',
      'wp-steel-roof-finishing',
    ],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-furniture-wood-factory',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Furnitures & Wood Works - Factory',
    description:
      'Factory pressing, cutting, and production. Already started and expected within the 30-45 day window.',
    assigneeName: 'Jithin',
    department: 'procurement_logistics',
    estimatedStartDate: '2026-05-18',
    estimatedEndDate: '2026-07-01',
    estimatedDurationDays: 45,
    status: 'in_progress',
    priority: 'critical',
    dependsOnWorkPackageIds: [],
    pausePeriods: [],
    manualOverrideEnabled: false,
    notes: 'Factory work is already ongoing.',
  },
  {
    id: 'wp-fixed-glass-sliding-part-b',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Fixed Glass Windows and Sliding Doors Part B',
    description:
      'Final glass and sliding door works after texture paint and before handover.',
    assigneeName: 'Akhil',
    department: 'design_execution',
    estimatedStartDate: '2026-06-28',
    estimatedEndDate: '2026-06-30',
    estimatedDurationDays: 3,
    status: 'blocked_by_payment',
    priority: 'high',
    paymentGateId: 'gate-after-texture-paint',
    dependsOnWorkPackageIds: ['wp-texture-paint-exterior'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-work-area-aluminium-cabinets',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Work Area Aluminium Cabinets',
    description:
      'Work area aluminium cabinet installation during the final site installation phase.',
    assigneeName: 'Akhil',
    department: 'design_execution',
    estimatedStartDate: '2026-06-29',
    estimatedEndDate: '2026-07-02',
    estimatedDurationDays: 4,
    status: 'blocked_by_payment',
    priority: 'high',
    paymentGateId: 'gate-after-texture-paint',
    dependsOnWorkPackageIds: ['wp-texture-paint-exterior'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-final-site-handover',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Final Site Adjustments / Handover Buffer',
    description:
      'Final checking, small corrections, finishing review, and handover preparation.',
    assigneeName: 'Site Supervisor',
    department: 'design_execution',
    estimatedStartDate: '2026-07-03',
    estimatedEndDate: '2026-07-04',
    estimatedDurationDays: 2,
    status: 'blocked_by_dependency',
    priority: 'critical',
    paymentGateId: 'gate-final-handover',
    dependsOnWorkPackageIds: [
      'wp-furniture-wood-factory',
      'wp-fixed-glass-sliding-part-b',
      'wp-work-area-aluminium-cabinets',
    ],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
];

export const demoTimelineAlerts: TimelineAlert[] = [
  {
    id: 'alert-major-payment',
    projectId: 'project-villa-athani',
    type: 'payment_blocker',
    severity: 'danger',
    title: 'Major site execution payment is pending',
    description:
      'Window fixing, exterior painting, and kitchen cabinet installation are blocked until this payment gate is marked received.',
    relatedWorkPackageIds: [
      'wp-window-fixing',
      'wp-exterior-paint',
      'wp-kitchen-cabinets',
    ],
    relatedPaymentGateIds: ['gate-major-site-execution'],
    suggestedShiftDays: 5,
    canApplySuggestion: true,
  },
  {
    id: 'alert-window-before-paint',
    projectId: 'project-villa-athani',
    type: 'dependency_conflict',
    severity: 'warning',
    title: 'Window fixing must finish before exterior painting',
    description:
      'Exterior painting is correctly blocked by the window fixing dependency to avoid damage and rework.',
    relatedWorkPackageIds: ['wp-window-fixing', 'wp-exterior-paint'],
    canApplySuggestion: false,
  },
  {
    id: 'alert-vendor-sequence',
    projectId: 'project-villa-athani',
    type: 'vendor_conflict',
    severity: 'info',
    title: 'Vendor sequencing needs confirmation',
    description:
      'Glass/window and kitchen cabinet works are handled by related vendor teams. Confirm sequence before shifting dates.',
    relatedWorkPackageIds: ['wp-window-fixing', 'wp-kitchen-cabinets'],
    canApplySuggestion: false,
  },
];
