import type {
  PaymentGate,
  TimelineAlert,
  TimelineProject,
  WorkPackage,
} from './types';

export const demoTimelineProject: TimelineProject = {
  id: 'project-villa-athani',
  name: 'Villa, Athani',
  clientName: 'Rafeek Muhammed Ali',
  projectType: 'Villa Interior',
  status: 'active',
  startDate: '2026-03-03',
  expectedHandoverDate: '2026-05-20',
  currentProjectedHandoverDate: '2026-05-24',
  revenue: 3145473,
  location: 'Athani, Kerala',
};

export const demoPaymentGates: PaymentGate[] = [
  {
    id: 'gate-design-advance',
    projectId: 'project-villa-athani',
    type: 'design_advance',
    title: 'Design Advance',
    description: 'Advance payment before planning and design work begins.',
    percentage: 50,
    amount: 75000,
    dueDate: '2026-03-03',
    receivedDate: '2026-03-03',
    status: 'received',
    blocksWorkPackageIds: ['wp-space-planning', 'wp-3d-design'],
  },
  {
    id: 'gate-design-balance',
    projectId: 'project-villa-athani',
    type: 'design_balance',
    title: 'Design Balance',
    description: 'Balance design fee payable after design approval if execution is dropped.',
    percentage: 50,
    amount: 75000,
    dueDate: '2026-03-18',
    receivedDate: '2026-03-18',
    status: 'received',
    blocksWorkPackageIds: ['wp-execution-planning'],
  },
  {
    id: 'gate-execution-booking',
    projectId: 'project-villa-athani',
    type: 'execution_booking',
    title: 'Execution Confirmation',
    description: 'Booking amount to confirm execution phase.',
    percentage: 10,
    amount: 314547,
    dueDate: '2026-03-22',
    receivedDate: '2026-03-22',
    status: 'received',
    blocksWorkPackageIds: ['wp-procurement-planning'],
  },
  {
    id: 'gate-procurement-start',
    projectId: 'project-villa-athani',
    type: 'procurement_start',
    title: 'Procurement Start',
    description: 'Payment required before procurement and production starts.',
    percentage: 30,
    amount: 943642,
    dueDate: '2026-03-28',
    receivedDate: '2026-04-02',
    status: 'received',
    blocksWorkPackageIds: [
      'wp-material-procurement',
      'wp-false-ceiling',
      'wp-electrical-rough-in',
    ],
  },
  {
    id: 'gate-major-site-execution',
    projectId: 'project-villa-athani',
    type: 'major_site_execution',
    title: 'Major Site Execution',
    description: 'Payment required before major site execution works continue.',
    percentage: 30,
    amount: 943642,
    dueDate: '2026-04-18',
    status: 'pending',
    blocksWorkPackageIds: [
      'wp-window-fixing',
      'wp-exterior-paint',
      'wp-kitchen-cabinets',
    ],
  },
  {
    id: 'gate-final-installation',
    projectId: 'project-villa-athani',
    type: 'final_installation',
    title: 'Final Installation',
    description: 'Payment required before final installation and finishing.',
    percentage: 20,
    amount: 629095,
    dueDate: '2026-05-05',
    status: 'pending',
    blocksWorkPackageIds: ['wp-final-fixtures', 'wp-snag-correction'],
  },
  {
    id: 'gate-handover',
    projectId: 'project-villa-athani',
    type: 'handover',
    title: 'Handover',
    description: 'Final payment before project handover.',
    percentage: 10,
    amount: 314547,
    dueDate: '2026-05-18',
    status: 'pending',
    blocksWorkPackageIds: ['wp-final-handover'],
  },
];

export const demoWorkPackages: WorkPackage[] = [
  {
    id: 'wp-space-planning',
    projectId: 'project-villa-athani',
    phase: 'design',
    title: 'Space Planning',
    description: 'Initial furniture layout, circulation planning, and zoning.',
    assigneeName: 'Design Lead',
    department: 'design_execution',
    estimatedStartDate: '2026-03-03',
    estimatedEndDate: '2026-03-08',
    estimatedDurationDays: 6,
    actualStartDate: '2026-03-03',
    actualEndDate: '2026-03-08',
    actualDurationDays: 6,
    status: 'completed',
    priority: 'high',
    paymentGateId: 'gate-design-advance',
    dependsOnWorkPackageIds: [],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-3d-design',
    projectId: 'project-villa-athani',
    phase: 'design',
    title: '3D Design & Material Direction',
    description: '3D views, material palette, and client presentation.',
    assigneeName: 'Senior Designer',
    department: 'design_execution',
    estimatedStartDate: '2026-03-09',
    estimatedEndDate: '2026-03-18',
    estimatedDurationDays: 10,
    actualStartDate: '2026-03-09',
    actualEndDate: '2026-03-19',
    actualDurationDays: 11,
    status: 'completed',
    priority: 'high',
    paymentGateId: 'gate-design-advance',
    dependsOnWorkPackageIds: ['wp-space-planning'],
    pausePeriods: [],
    manualOverrideEnabled: false,
    notes: 'Client requested one material revision.',
  },
  {
    id: 'wp-execution-planning',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Execution Planning',
    description: 'Execution scope, work sequencing, vendor assignment, and site readiness planning.',
    assigneeName: 'Execution Head',
    department: 'design_execution',
    estimatedStartDate: '2026-03-20',
    estimatedEndDate: '2026-03-25',
    estimatedDurationDays: 6,
    actualStartDate: '2026-03-20',
    actualEndDate: '2026-03-26',
    actualDurationDays: 7,
    status: 'completed',
    priority: 'critical',
    paymentGateId: 'gate-design-balance',
    dependsOnWorkPackageIds: ['wp-3d-design'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-procurement-planning',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Procurement Planning',
    description: 'Material list, vendor confirmations, and procurement schedule.',
    assigneeName: 'Procurement Lead',
    department: 'procurement_logistics',
    estimatedStartDate: '2026-03-26',
    estimatedEndDate: '2026-03-29',
    estimatedDurationDays: 4,
    actualStartDate: '2026-03-27',
    actualEndDate: '2026-04-02',
    actualDurationDays: 7,
    status: 'delayed',
    priority: 'critical',
    paymentGateId: 'gate-execution-booking',
    dependsOnWorkPackageIds: ['wp-execution-planning'],
    pausePeriods: [
      {
        id: 'pause-procurement-payment-delay',
        pauseStart: '2026-03-29',
        pauseEnd: '2026-04-02',
        reason: 'Procurement payment was delayed by client.',
        createdBy: 'Finance',
      },
    ],
    manualOverrideEnabled: false,
    notes: 'Procurement start shifted due to delayed payment.',
  },
  {
    id: 'wp-material-procurement',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Material Procurement',
    description: 'Ordering laminate, hardware, lighting, gypsum material, and accessories.',
    assigneeName: 'Procurement Lead',
    department: 'procurement_logistics',
    estimatedStartDate: '2026-04-01',
    estimatedEndDate: '2026-04-10',
    estimatedDurationDays: 10,
    actualStartDate: '2026-04-03',
    actualEndDate: '2026-04-13',
    actualDurationDays: 11,
    status: 'completed',
    priority: 'critical',
    paymentGateId: 'gate-procurement-start',
    dependsOnWorkPackageIds: ['wp-procurement-planning'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-false-ceiling',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'False Ceiling Work',
    description: 'Gypsum ceiling framework, board fixing, and cove preparation.',
    vendorId: 'vendor-false-ceiling',
    assigneeName: 'Site Supervisor',
    department: 'design_execution',
    estimatedStartDate: '2026-04-05',
    estimatedEndDate: '2026-04-14',
    estimatedDurationDays: 10,
    actualStartDate: '2026-04-06',
    actualEndDate: '2026-04-16',
    actualDurationDays: 11,
    status: 'completed',
    priority: 'high',
    paymentGateId: 'gate-procurement-start',
    dependsOnWorkPackageIds: ['wp-material-procurement'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-electrical-rough-in',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Electrical Rough-in',
    description: 'Lighting points, switch points, DB checks, and concealed wiring coordination.',
    vendorId: 'vendor-electrical',
    assigneeName: 'Site Supervisor',
    department: 'design_execution',
    estimatedStartDate: '2026-04-10',
    estimatedEndDate: '2026-04-17',
    estimatedDurationDays: 8,
    actualStartDate: '2026-04-11',
    actualEndDate: '2026-04-18',
    actualDurationDays: 8,
    status: 'completed',
    priority: 'high',
    paymentGateId: 'gate-procurement-start',
    dependsOnWorkPackageIds: ['wp-false-ceiling'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-texture-interior-paint',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Interior Texture Painting',
    description: 'Interior wall texture and paint work before exterior sequence begins.',
    vendorId: 'vendor-texture-paint',
    assigneeName: 'Site Supervisor',
    department: 'design_execution',
    estimatedStartDate: '2026-04-16',
    estimatedEndDate: '2026-04-24',
    estimatedDurationDays: 9,
    actualStartDate: '2026-04-19',
    actualEndDate: '2026-04-28',
    actualDurationDays: 10,
    status: 'paused',
    priority: 'high',
    dependsOnWorkPackageIds: ['wp-electrical-rough-in'],
    pausePeriods: [
      {
        id: 'pause-texture-before-window',
        pauseStart: '2026-04-24',
        pauseEnd: '2026-04-26',
        reason: 'Paused exterior side to complete glass/window fixing before painting.',
        createdBy: 'Execution Head',
      },
    ],
    manualOverrideEnabled: true,
    overrideReason: 'Manual sequencing to avoid damage after window work.',
  },
  {
    id: 'wp-window-fixing',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Glass Window Fixing',
    description: 'Fix glass windows before exterior painting to prevent paint damage.',
    vendorId: 'vendor-glass-windows',
    assigneeName: 'Vendor Coordinator',
    department: 'procurement_logistics',
    estimatedStartDate: '2026-04-24',
    estimatedEndDate: '2026-04-29',
    estimatedDurationDays: 6,
    actualStartDate: '2026-04-27',
    status: 'blocked_by_payment',
    priority: 'critical',
    paymentGateId: 'gate-major-site-execution',
    dependsOnWorkPackageIds: ['wp-texture-interior-paint'],
    pausePeriods: [
      {
        id: 'pause-window-payment',
        pauseStart: '2026-04-27',
        reason: 'Work held because major site execution payment is pending.',
        createdBy: 'Finance',
      },
    ],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-exterior-paint',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Exterior Painting',
    description: 'Exterior painting continues after window fixing to prevent rework.',
    vendorId: 'vendor-texture-paint',
    assigneeName: 'Site Supervisor',
    department: 'design_execution',
    estimatedStartDate: '2026-04-30',
    estimatedEndDate: '2026-05-05',
    estimatedDurationDays: 6,
    status: 'blocked_by_dependency',
    priority: 'critical',
    paymentGateId: 'gate-major-site-execution',
    dependsOnWorkPackageIds: ['wp-window-fixing'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-kitchen-cabinets',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Kitchen Cabinet Installation',
    description: 'Kitchen cabinet installation after painting and site readiness.',
    vendorId: 'vendor-kitchen-cabinet',
    assigneeName: 'Vendor Coordinator',
    department: 'procurement_logistics',
    estimatedStartDate: '2026-05-06',
    estimatedEndDate: '2026-05-14',
    estimatedDurationDays: 9,
    status: 'blocked_by_payment',
    priority: 'high',
    paymentGateId: 'gate-major-site-execution',
    dependsOnWorkPackageIds: ['wp-exterior-paint'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-final-fixtures',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Final Fixtures & Lighting',
    description: 'Final lights, accessories, hardware, and visible finishing works.',
    vendorId: 'vendor-electrical',
    assigneeName: 'Site Supervisor',
    department: 'design_execution',
    estimatedStartDate: '2026-05-13',
    estimatedEndDate: '2026-05-17',
    estimatedDurationDays: 5,
    status: 'blocked_by_payment',
    priority: 'medium',
    paymentGateId: 'gate-final-installation',
    dependsOnWorkPackageIds: ['wp-kitchen-cabinets'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-snag-correction',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Snag Correction',
    description: 'Final corrections, touch-ups, cleaning and quality checks.',
    assigneeName: 'Execution Head',
    department: 'design_execution',
    estimatedStartDate: '2026-05-17',
    estimatedEndDate: '2026-05-19',
    estimatedDurationDays: 3,
    status: 'blocked_by_dependency',
    priority: 'medium',
    paymentGateId: 'gate-final-installation',
    dependsOnWorkPackageIds: ['wp-final-fixtures'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
  {
    id: 'wp-final-handover',
    projectId: 'project-villa-athani',
    phase: 'execution',
    title: 'Final Handover',
    description: 'Client walkthrough, handover confirmation, and closure notes.',
    assigneeName: 'Admin',
    department: 'admin',
    estimatedStartDate: '2026-05-20',
    estimatedEndDate: '2026-05-20',
    estimatedDurationDays: 1,
    status: 'blocked_by_dependency',
    priority: 'critical',
    paymentGateId: 'gate-handover',
    dependsOnWorkPackageIds: ['wp-snag-correction'],
    pausePeriods: [],
    manualOverrideEnabled: false,
  },
];

export const demoTimelineAlerts: TimelineAlert[] = [
  {
    id: 'alert-major-payment',
    projectId: 'project-villa-athani',
    type: 'payment_blocker',
    severity: 'danger',
    title: 'Major site execution payment is pending',
    description:
      'Window fixing, exterior painting, and kitchen cabinet installation are blocked until this payment gate is marked received.',
    relatedWorkPackageIds: [
      'wp-window-fixing',
      'wp-exterior-paint',
      'wp-kitchen-cabinets',
    ],
    relatedPaymentGateIds: ['gate-major-site-execution'],
    suggestedShiftDays: 5,
    canApplySuggestion: true,
  },
  {
    id: 'alert-window-before-paint',
    projectId: 'project-villa-athani',
    type: 'dependency_conflict',
    severity: 'warning',
    title: 'Window fixing must finish before exterior painting',
    description:
      'Exterior painting is correctly blocked by the window fixing dependency to avoid damage and rework.',
    relatedWorkPackageIds: ['wp-window-fixing', 'wp-exterior-paint'],
    canApplySuggestion: false,
  },
  {
    id: 'alert-vendor-sequence',
    projectId: 'project-villa-athani',
    type: 'vendor_conflict',
    severity: 'info',
    title: 'Vendor sequencing needs confirmation',
    description:
      'Glass/window and kitchen cabinet works are handled by related vendor teams. Confirm sequence before shifting dates.',
    relatedWorkPackageIds: ['wp-window-fixing', 'wp-kitchen-cabinets'],
    canApplySuggestion: false,
  },
];