import type {
  AreaTemplate,
  PaymentTemplateItem,
  ProjectCategory,
  ProjectTimelineMode,
  ScopeItemTemplate,
  TimelineTemplate,
} from './scopeTypes';

export const projectCategoryLabels: Record<ProjectCategory, string> = {
  new_home_interior: 'New Home Interior',
  renovation: 'Renovation',
  exterior: 'Exterior',
  room_specific: 'Room Specific',
  design_only: 'Design Only',
  execution_only: 'Execution Only',
};

export const timelineModeLabels: Record<ProjectTimelineMode, string> = {
  design_only: 'Design Only',
  execution_only: 'Execution Only',
  design_execution: 'Design + Execution',
};

export const areaTemplates: AreaTemplate[] = [
  {
    id: 'area-full-house',
    type: 'full_house',
    name: 'Full House',
    description: 'Whole-home interior scope including common areas, bedrooms, kitchen, and support spaces.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-site-measurement',
      'scope-space-planning',
      'scope-3d-design',
      'scope-material-selection',
      'scope-electrical',
      'scope-false-ceiling',
      'scope-painting',
      'scope-final-fixtures',
      'scope-snag-correction',
    ],
  },
  {
    id: 'area-living-room',
    type: 'living_room',
    name: 'Living Room',
    description: 'Living room interior scope such as ceiling, TV unit, wall panels, lighting, furniture, doors, and windows.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-false-ceiling',
      'scope-tv-unit',
      'scope-wall-panel',
      'scope-loose-furniture',
      'scope-aluminium-sliding-door',
      'scope-window-work',
      'scope-lighting',
      'scope-painting',
    ],
  },
  {
    id: 'area-kitchen',
    type: 'kitchen',
    name: 'Kitchen',
    description: 'Kitchen cabinetry, countertop, backsplash, plumbing, electrical, and appliance coordination.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-modular-kitchen',
      'scope-countertop',
      'scope-backsplash',
      'scope-plumbing',
      'scope-electrical',
      'scope-lighting',
    ],
  },
  {
    id: 'area-bedroom',
    type: 'bedroom',
    name: 'Bedroom',
    description: 'Bedroom wardrobe, bed back panel, ceiling, painting, curtains, and furniture.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-wardrobe',
      'scope-bed-back-panel',
      'scope-false-ceiling',
      'scope-painting',
      'scope-curtains',
      'scope-loose-furniture',
    ],
  },
  {
    id: 'area-bathroom',
    type: 'bathroom',
    name: 'Bathroom',
    description: 'Bathroom renovation, plumbing, fixtures, tile correction, lighting, and accessories.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-plumbing',
      'scope-tile-work',
      'scope-bathroom-fixtures',
      'scope-lighting',
    ],
  },
  {
    id: 'area-exterior',
    type: 'exterior',
    name: 'Exterior',
    description: 'Exterior painting, facade, window coordination, outdoor lighting, and exterior feature work.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-window-work',
      'scope-exterior-painting',
      'scope-exterior-lighting',
      'scope-facade-panel',
    ],
  },
  {
    id: 'area-prayer-room',
    type: 'prayer_room',
    name: 'Prayer Room',
    description: 'Prayer room custom feature wall, CNC panels, lighting, floor mat, and storage.',
    isCustom: false,
    defaultScopeItemIds: [
      'scope-cnc-arabesque-panel',
      'scope-prayer-room-arch-feature',
      'scope-floor-mat',
      'scope-lighting',
      'scope-custom-storage',
      'scope-painting',
    ],
  },
  {
    id: 'area-custom',
    type: 'custom',
    name: 'Custom Area',
    description: 'Use this for custom spaces such as majlis, library, gym, pooja room, home office, or special-purpose rooms.',
    isCustom: true,
    defaultScopeItemIds: [],
  },
];

export const scopeItemTemplates: ScopeItemTemplate[] = [
  {
    id: 'scope-site-measurement',
    name: 'Site Measurement',
    description: 'Site measurement, verification, and initial technical checks.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 2,
    defaultPriority: 'critical',
    vendorRequired: false,
    dependencyRules: ['after_design_approval'],
    complexity: 'simple',
    createsWorkPackage: true,
  },
  {
    id: 'scope-space-planning',
    name: 'Space Planning',
    description: 'Furniture layout, circulation, zoning, and concept planning.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'custom'],
    defaultPhase: 'design',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 5,
    defaultPriority: 'high',
    vendorRequired: false,
    defaultPaymentGateType: 'design_advance',
    dependencyRules: ['after_design_approval'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-3d-design',
    name: '3D Design',
    description: '3D visualization, material direction, and design presentation.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'exterior', 'custom'],
    defaultPhase: 'design',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 8,
    defaultPriority: 'high',
    vendorRequired: false,
    defaultPaymentGateType: 'design_advance',
    dependencyRules: ['after_design_approval'],
    complexity: 'premium',
    createsWorkPackage: true,
  },
  {
    id: 'scope-material-selection',
    name: 'Material Selection',
    description: 'Material palette, laminate, fabric, paint, hardware, and finish selections.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'custom'],
    defaultPhase: 'design',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 4,
    defaultPriority: 'high',
    vendorRequired: false,
    defaultPaymentGateType: 'design_advance',
    dependencyRules: ['after_design_approval'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-electrical',
    name: 'Electrical Work',
    description: 'Electrical rough-in, switch points, lighting points, DB coordination, and fixture installation.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 6,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'electrical',
    defaultPaymentGateType: 'procurement_start',
    dependencyRules: ['after_site_measurement', 'before_final_fixtures'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-plumbing',
    name: 'Plumbing Work',
    description: 'Kitchen or bathroom plumbing, drainage corrections, and concealed line changes.',
    allowedAreaTypes: ['full_house', 'kitchen', 'bathroom', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 5,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'plumbing',
    defaultPaymentGateType: 'procurement_start',
    dependencyRules: ['after_site_measurement', 'after_civil_readiness'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-false-ceiling',
    name: 'False Ceiling',
    description: 'Gypsum ceiling framework, board fixing, cove lighting preparation, and finishing.',
    allowedAreaTypes: ['full_house', 'living_room', 'bedroom', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 8,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'false_ceiling',
    defaultPaymentGateType: 'procurement_start',
    dependencyRules: ['after_material_procurement', 'after_electrical_rough_in'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-tv-unit',
    name: 'TV Unit Cabinet',
    description: 'TV unit production, wall mounting, panel coordination, and final installation.',
    allowedAreaTypes: ['living_room', 'full_house', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 7,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'carpentry',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement', 'after_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-wall-panel',
    name: 'Wall Panel',
    description: 'Decorative wall panel production and installation.',
    allowedAreaTypes: ['living_room', 'bedroom', 'prayer_room', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 6,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'carpentry',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement', 'after_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-cnc-arabesque-panel',
    name: 'CNC Arabesque Wall Panel',
    description: 'Custom CNC cut wall panel with Arabesque or Islamic geometric patterns.',
    allowedAreaTypes: ['prayer_room', 'pooja_room', 'living_room', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 10,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'carpentry',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_design_approval', 'after_site_measurement', 'after_material_procurement'],
    complexity: 'custom',
    createsWorkPackage: true,
  },
  {
    id: 'scope-prayer-room-arch-feature',
    name: 'Prayer Room Arch Feature',
    description: 'Decorative arch feature wall inspired by mosque or Islamic architectural forms.',
    allowedAreaTypes: ['prayer_room', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 7,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'carpentry',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_design_approval', 'after_material_procurement'],
    complexity: 'custom',
    createsWorkPackage: true,
  },
  {
    id: 'scope-floor-mat',
    name: 'Floor Mat / Carpet Zone',
    description: 'Floor mat, carpet, or prayer mat placement zone with final sizing and procurement.',
    allowedAreaTypes: ['prayer_room', 'bedroom', 'living_room', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 2,
    defaultPriority: 'low',
    vendorRequired: true,
    vendorCategory: 'fabrication',
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['after_painting'],
    complexity: 'simple',
    createsWorkPackage: true,
  },
  {
    id: 'scope-aluminium-sliding-door',
    name: 'Aluminium Sliding Door',
    description: 'Aluminium sliding door measurement, fabrication, fixing, and alignment.',
    allowedAreaTypes: ['living_room', 'bedroom', 'balcony', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 6,
    defaultPriority: 'critical',
    vendorRequired: true,
    vendorCategory: 'glass_windows',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_site_measurement', 'before_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-window-work',
    name: 'Windows / Glass Work',
    description: 'Window fixing, glass work, aluminium frames, partitions, or balcony glass.',
    allowedAreaTypes: ['full_house', 'living_room', 'bedroom', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 6,
    defaultPriority: 'critical',
    vendorRequired: true,
    vendorCategory: 'glass_windows',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_site_measurement', 'before_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-modular-kitchen',
    name: 'Modular Kitchen',
    description: 'Kitchen cabinet production, shutters, hardware, accessories, and installation.',
    allowedAreaTypes: ['kitchen', 'full_house'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 12,
    defaultPriority: 'critical',
    vendorRequired: true,
    vendorCategory: 'modular_kitchen',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement', 'after_painting'],
    complexity: 'premium',
    createsWorkPackage: true,
  },
  {
    id: 'scope-wardrobe',
    name: 'Wardrobe',
    description: 'Wardrobe production, hardware, shutters, accessories, and installation.',
    allowedAreaTypes: ['bedroom', 'full_house', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 10,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'wardrobe',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement', 'after_painting'],
    complexity: 'premium',
    createsWorkPackage: true,
  },
  {
    id: 'scope-painting',
    name: 'Interior Painting',
    description: 'Interior painting, texture paint, wall putty, primer, and finish coat.',
    allowedAreaTypes: ['full_house', 'living_room', 'bedroom', 'bathroom', 'prayer_room', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 7,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'painting',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_false_ceiling', 'after_electrical_rough_in'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-exterior-painting',
    name: 'Exterior Painting',
    description: 'Exterior wall painting, texture, waterproofing coordination, and final coat.',
    allowedAreaTypes: ['exterior', 'full_house'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 6,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'painting',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_window_fixing'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-lighting',
    name: 'Lighting',
    description: 'Decorative lighting, profile lighting, ambient lighting, and fixture placement.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'prayer_room', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 3,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'lighting',
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['before_final_fixtures'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-final-fixtures',
    name: 'Final Fixtures',
    description: 'Final visible fixtures, accessories, hardware, lighting, and finishing works.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 4,
    defaultPriority: 'medium',
    vendorRequired: false,
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['before_final_fixtures'],
    complexity: 'simple',
    createsWorkPackage: true,
  },
  {
    id: 'scope-snag-correction',
    name: 'Snag Correction',
    description: 'Final corrections, quality check, touch-ups, and handover preparation.',
    allowedAreaTypes: ['full_house', 'living_room', 'kitchen', 'bedroom', 'bathroom', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 3,
    defaultPriority: 'medium',
    vendorRequired: false,
    defaultPaymentGateType: 'handover',
    dependencyRules: ['before_final_fixtures'],
    complexity: 'simple',
    createsWorkPackage: true,
  },
  {
    id: 'scope-loose-furniture',
    name: 'Loose Furniture',
    description: 'Furniture selection, ordering, delivery, and placement.',
    allowedAreaTypes: ['living_room', 'bedroom', 'dining', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 5,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'other',
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['after_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-custom-storage',
    name: 'Custom Storage',
    description: 'Custom cabinet, storage unit, or niche storage requirement.',
    allowedAreaTypes: ['prayer_room', 'bedroom', 'living_room', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 6,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'carpentry',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement', 'after_painting'],
    complexity: 'custom',
    createsWorkPackage: true,
  },
  {
    id: 'scope-bed-back-panel',
    name: 'Bed Back Panel',
    description: 'Bedroom bed back panel production and installation.',
    allowedAreaTypes: ['bedroom', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 6,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'carpentry',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement', 'after_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-curtains',
    name: 'Curtains / Soft Furnishing',
    description: 'Curtains, blinds, measurements, fabric selection, and installation.',
    allowedAreaTypes: ['living_room', 'bedroom', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 4,
    defaultPriority: 'low',
    vendorRequired: true,
    vendorCategory: 'other',
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['after_painting'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-countertop',
    name: 'Countertop',
    description: 'Kitchen countertop measurement, fabrication, and installation.',
    allowedAreaTypes: ['kitchen'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 5,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'stone',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_material_procurement'],
    complexity: 'premium',
    createsWorkPackage: true,
  },
  {
    id: 'scope-backsplash',
    name: 'Backsplash',
    description: 'Kitchen backsplash tile, stone, or panel installation.',
    allowedAreaTypes: ['kitchen'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 3,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'stone',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_civil_readiness'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-tile-work',
    name: 'Tile Work',
    description: 'Tile laying, correction, levelling, and grout finishing.',
    allowedAreaTypes: ['bathroom', 'kitchen', 'exterior', 'custom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 7,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'flooring',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_civil_readiness'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-bathroom-fixtures',
    name: 'Bathroom Fixtures',
    description: 'Sanitary fixtures, accessories, mirror, lighting, and final fit-off.',
    allowedAreaTypes: ['bathroom'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 4,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'plumbing',
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['before_final_fixtures'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-exterior-lighting',
    name: 'Exterior Lighting',
    description: 'Exterior lighting points, fixtures, and final installation.',
    allowedAreaTypes: ['exterior'],
    defaultPhase: 'execution',
    defaultDepartment: 'design_execution',
    defaultDurationDays: 3,
    defaultPriority: 'medium',
    vendorRequired: true,
    vendorCategory: 'lighting',
    defaultPaymentGateType: 'final_installation',
    dependencyRules: ['before_final_fixtures'],
    complexity: 'standard',
    createsWorkPackage: true,
  },
  {
    id: 'scope-facade-panel',
    name: 'Facade Panel',
    description: 'Exterior facade panel, cladding, or decorative exterior feature.',
    allowedAreaTypes: ['exterior'],
    defaultPhase: 'execution',
    defaultDepartment: 'procurement_logistics',
    defaultDurationDays: 8,
    defaultPriority: 'high',
    vendorRequired: true,
    vendorCategory: 'fabrication',
    defaultPaymentGateType: 'major_site_execution',
    dependencyRules: ['after_site_measurement'],
    complexity: 'premium',
    createsWorkPackage: true,
  },
];

export const designPaymentTemplate: PaymentTemplateItem[] = [
  {
    id: 'payment-design-advance',
    type: 'design_advance',
    title: 'Design Advance',
    description: 'Payment before planning and design work starts.',
    phase: 'design',
    percentage: 50,
    blocksScopeItemTemplateIds: [
      'scope-space-planning',
      'scope-3d-design',
      'scope-material-selection',
    ],
  },
  {
    id: 'payment-design-balance',
    type: 'design_balance',
    title: 'Design Balance',
    description: 'Balance payment after design approval or before closing as design-only.',
    phase: 'design',
    percentage: 50,
    blocksScopeItemTemplateIds: [],
  },
];

export const executionPaymentTemplate: PaymentTemplateItem[] = [
  {
    id: 'payment-execution-booking',
    type: 'execution_booking',
    title: 'Execution Confirmation',
    description: 'Booking amount to confirm execution.',
    phase: 'execution',
    percentage: 10,
    blocksScopeItemTemplateIds: ['scope-site-measurement'],
  },
  {
    id: 'payment-procurement-start',
    type: 'procurement_start',
    title: 'Procurement Start',
    description: 'Payment required before procurement and production starts.',
    phase: 'execution',
    percentage: 30,
    blocksScopeItemTemplateIds: [
      'scope-electrical',
      'scope-plumbing',
      'scope-false-ceiling',
      'scope-material-selection',
    ],
  },
  {
    id: 'payment-major-site-execution',
    type: 'major_site_execution',
    title: 'Major Site Execution',
    description: 'Payment required before major vendor works continue.',
    phase: 'execution',
    percentage: 30,
    blocksScopeItemTemplateIds: [
      'scope-tv-unit',
      'scope-wall-panel',
      'scope-cnc-arabesque-panel',
      'scope-aluminium-sliding-door',
      'scope-window-work',
      'scope-modular-kitchen',
      'scope-wardrobe',
      'scope-painting',
      'scope-exterior-painting',
    ],
  },
  {
    id: 'payment-final-installation',
    type: 'final_installation',
    title: 'Final Installation',
    description: 'Payment required before final fixtures and finishing.',
    phase: 'execution',
    percentage: 20,
    blocksScopeItemTemplateIds: [
      'scope-lighting',
      'scope-floor-mat',
      'scope-final-fixtures',
      'scope-curtains',
      'scope-bathroom-fixtures',
      'scope-exterior-lighting',
    ],
  },
  {
    id: 'payment-handover',
    type: 'handover',
    title: 'Handover',
    description: 'Final payment before project handover.',
    phase: 'execution',
    percentage: 10,
    blocksScopeItemTemplateIds: ['scope-snag-correction'],
  },
];

export const timelineTemplates: TimelineTemplate[] = [
  {
    id: 'template-design-only',
    name: 'Design Only',
    description: 'Design-only workflow that can later convert into execution.',
    projectCategories: ['design_only'],
    defaultTimelineMode: 'design_only',
    supportsConversionToExecution: true,
    areaTemplateIds: ['area-full-house', 'area-living-room', 'area-kitchen', 'area-bedroom', 'area-custom'],
    paymentTemplate: designPaymentTemplate,
  },
  {
    id: 'template-new-home-interior',
    name: 'New Home Interior',
    description: 'Full interior project with design, execution, procurement, vendors, and handover payment gates.',
    projectCategories: ['new_home_interior'],
    defaultTimelineMode: 'design_execution',
    supportsConversionToExecution: false,
    areaTemplateIds: ['area-full-house', 'area-living-room', 'area-kitchen', 'area-bedroom', 'area-prayer-room', 'area-custom'],
    paymentTemplate: [...designPaymentTemplate, ...executionPaymentTemplate],
  },
  {
    id: 'template-renovation',
    name: 'Renovation',
    description: 'Renovation project with flexible custom scope, civil readiness, procurement, and execution.',
    projectCategories: ['renovation'],
    defaultTimelineMode: 'design_execution',
    supportsConversionToExecution: false,
    areaTemplateIds: ['area-living-room', 'area-kitchen', 'area-bedroom', 'area-bathroom', 'area-custom'],
    paymentTemplate: [...designPaymentTemplate, ...executionPaymentTemplate],
  },
  {
    id: 'template-exterior',
    name: 'Exterior',
    description: 'Exterior facade, window, painting, lighting, and exterior feature workflow.',
    projectCategories: ['exterior'],
    defaultTimelineMode: 'execution_only',
    supportsConversionToExecution: false,
    areaTemplateIds: ['area-exterior', 'area-custom'],
    paymentTemplate: executionPaymentTemplate,
  },
  {
    id: 'template-room-specific',
    name: 'Room Specific',
    description: 'Single-room or selected-room execution with custom scope items.',
    projectCategories: ['room_specific'],
    defaultTimelineMode: 'design_execution',
    supportsConversionToExecution: false,
    areaTemplateIds: ['area-living-room', 'area-kitchen', 'area-bedroom', 'area-prayer-room', 'area-custom'],
    paymentTemplate: [...designPaymentTemplate, ...executionPaymentTemplate],
  },
  {
    id: 'template-execution-only',
    name: 'Execution Only',
    description: 'Execution-only workflow when design is already approved or provided externally.',
    projectCategories: ['execution_only'],
    defaultTimelineMode: 'execution_only',
    supportsConversionToExecution: false,
    areaTemplateIds: ['area-full-house', 'area-living-room', 'area-kitchen', 'area-bedroom', 'area-exterior', 'area-custom'],
    paymentTemplate: executionPaymentTemplate,
  },
];

export function getTimelineTemplateById(templateId?: string) {
  if (!templateId) return undefined;

  return timelineTemplates.find(template => template.id === templateId);
}

export function getAreaTemplateById(areaTemplateId?: string) {
  if (!areaTemplateId) return undefined;

  return areaTemplates.find(areaTemplate => areaTemplate.id === areaTemplateId);
}

export function getScopeItemTemplateById(scopeItemTemplateId?: string) {
  if (!scopeItemTemplateId) return undefined;

  return scopeItemTemplates.find(scopeItem => scopeItem.id === scopeItemTemplateId);
}

export function getScopeItemsForAreaType(areaType: AreaTemplate['type']) {
  return scopeItemTemplates.filter(scopeItem =>
    scopeItem.allowedAreaTypes.includes(areaType)
  );
}

export function getDefaultScopeItemsForArea(areaTemplateId: string) {
  const areaTemplate = getAreaTemplateById(areaTemplateId);

  if (!areaTemplate) return [];

  return areaTemplate.defaultScopeItemIds
    .map(scopeItemId => getScopeItemTemplateById(scopeItemId))
    .filter(Boolean) as ScopeItemTemplate[];
}
