import type { Vendor } from './types';

export const demoVendors: Vendor[] = [
  {
    id: 'vendor-texture-paint',
    name: 'Premium Texture Works',
    category: 'painting',
    scopeOfWork: 'Interior texture paint, exterior paint, wall finishes',
    contactPerson: 'Shameer',
    phone: '+91 98765 43210',
    email: 'textureworks@example.com',
    location: 'Kochi',
    rating: 4.6,
    status: 'active',
    availability: 'busy',
    assignedProjectCount: 2,
    notes: 'Reliable for premium texture finishes. Requires clear surface preparation before arrival.',
    createdAt: '2026-03-01',
    updatedAt: '2026-05-10',
  },
  {
    id: 'vendor-glass-windows',
    name: 'ClearView Glass & Windows',
    category: 'glass_windows',
    scopeOfWork: 'Glass windows, aluminium frames, balcony glass, partitions',
    contactPerson: 'Niyas',
    phone: '+91 98765 43211',
    email: 'clearview@example.com',
    location: 'Ernakulam',
    rating: 4.4,
    status: 'active',
    availability: 'available',
    assignedProjectCount: 1,
    notes: 'Also handles selected kitchen cabinet glass shutter works.',
    createdAt: '2026-03-02',
    updatedAt: '2026-05-10',
  },
  {
    id: 'vendor-kitchen-cabinet',
    name: 'CraftLine Modular Interiors',
    category: 'modular_kitchen',
    scopeOfWork: 'Kitchen cabinets, wardrobes, shutters, hardware installation',
    contactPerson: 'Rashid',
    phone: '+91 98765 43212',
    email: 'craftline@example.com',
    location: 'Aluva',
    rating: 4.7,
    status: 'active',
    availability: 'busy',
    assignedProjectCount: 3,
    notes: 'Good finish quality. Needs final design freeze before production.',
    createdAt: '2026-03-03',
    updatedAt: '2026-05-10',
  },
  {
    id: 'vendor-electrical',
    name: 'VoltEdge Electricals',
    category: 'electrical',
    scopeOfWork: 'Electrical wiring, DB works, lighting points, fixture installation',
    contactPerson: 'Ajmal',
    phone: '+91 98765 43213',
    email: 'voltedge@example.com',
    location: 'Kakkanad',
    rating: 4.3,
    status: 'active',
    availability: 'available',
    assignedProjectCount: 1,
    notes: 'Best used with clear lighting layout and marked site drawings.',
    createdAt: '2026-03-04',
    updatedAt: '2026-05-10',
  },
  {
    id: 'vendor-plumbing',
    name: 'FlowLine Plumbing Works',
    category: 'plumbing',
    scopeOfWork: 'Bathroom plumbing, kitchen plumbing, drainage corrections',
    contactPerson: 'Sajeev',
    phone: '+91 98765 43214',
    location: 'Kochi',
    rating: 4.1,
    status: 'active',
    availability: 'on_hold',
    assignedProjectCount: 1,
    notes: 'Needs supervision during concealed line changes.',
    createdAt: '2026-03-05',
    updatedAt: '2026-05-10',
  },
  {
    id: 'vendor-false-ceiling',
    name: 'CeilPro Gypsum Works',
    category: 'false_ceiling',
    scopeOfWork: 'Gypsum ceiling, cove lighting, ceiling framework',
    contactPerson: 'Muneer',
    phone: '+91 98765 43215',
    email: 'ceilpro@example.com',
    location: 'Edappally',
    rating: 4.5,
    status: 'active',
    availability: 'available',
    assignedProjectCount: 2,
    notes: 'Coordinates well with electrical team when drawings are clear.',
    createdAt: '2026-03-06',
    updatedAt: '2026-05-10',
  },
  {
    id: 'vendor-civil',
    name: 'BuildCore Civil Contractors',
    category: 'civil',
    scopeOfWork: 'Civil modifications, masonry, tile base corrections, site prep',
    contactPerson: 'Noushad',
    phone: '+91 98765 43216',
    location: 'Thrippunithura',
    rating: 4.2,
    status: 'active',
    availability: 'busy',
    assignedProjectCount: 2,
    notes: 'Good for early-stage execution corrections and site preparation.',
    createdAt: '2026-03-07',
    updatedAt: '2026-05-10',
  },
];

export const vendorCategoryLabels: Record<Vendor['category'], string> = {
  civil: 'Civil',
  electrical: 'Electrical',
  plumbing: 'Plumbing',
  painting: 'Painting',
  false_ceiling: 'False Ceiling',
  glass_windows: 'Glass & Windows',
  carpentry: 'Carpentry',
  modular_kitchen: 'Modular Kitchen',
  wardrobe: 'Wardrobe',
  flooring: 'Flooring',
  stone: 'Stone',
  metal: 'Metal',
  fabrication: 'Fabrication',
  lighting: 'Lighting',
  other: 'Other',
};

export const vendorStatusLabels: Record<Vendor['status'], string> = {
  active: 'Active',
  inactive: 'Inactive',
  blacklisted: 'Blacklisted',
};

export const vendorAvailabilityLabels: Record<Vendor['availability'], string> = {
  available: 'Available',
  busy: 'Busy',
  on_hold: 'On Hold',
};
